before_install:
   - nvm install 7 # pour PythonV3.6
   - npm i -g npm@7.11.2
language: node_js
node_js:
  - "stable"
script:
  - npm run build
  - npm run test
deploy:
  provider: pages
  skip_cleanup: true
  github_token: $github_token
  local_dir: build
  on:
    branch: sensei
branches:
  only:
    - pre-prod
