language: node_js
node_js:
  - "stable"
script:
  - npm run build
  - npm run test
deploy:
  provider: pages
  skip_cleanup: true
  github_token: $github_token
  local_dir: build
  on:
    branch: sensei
branches:
  only:
    - pre-prod
